var list = document.getElementById("monList");
var dexNum = document.getElementById("dexNum");
var monName = document.getElementById("monName");
var catchRate = document.getElementById("catchRate");
var catchRate2 = document.getElementById("catchRate2");
var listOutput = document.getElementById("listOutput");

console.log("add enter submit");

function loadFromSelect() {
    var currentMon;
    for (var mon of mons) {
        if (mon.name === list.value) {
            currentMon = mon;
        }
    }
    if (currentMon !== undefined) {
        dexNum.value = currentMon.dex;
        monName.value = currentMon.name;
        catchRate.value = currentMon.cr;
    }
}

function loadFromDex() {
    var currentMon;
    for (var mon of mons) {
        if (mon.dex === parseInt(dexNum.value)) {
            currentMon = mon;
        }
    }
    if (currentMon !== undefined) {
        list.value = currentMon.name;
        monName.value = currentMon.name;
        catchRate.value = currentMon.cr;
    }
}

function loadFromName() {
    var currentMon;
    for (var mon of mons) {
        if (mon.name === monName.value) {
            currentMon = mon;
        }
    }
    if (currentMon !== undefined) {
        list.value = currentMon.name;
        dexNum.value = currentMon.dex;
        catchRate.value = currentMon.cr;
    }
}

list.addEventListener("change", function() {
    loadFromSelect();
});
dexNum.addEventListener("input", function() {
    loadFromDex();
});
monName.addEventListener("input", function() {
    loadFromName();
});

function listMons() {
	var cr = parseInt(catchRate2.value);
	listOutput.innerHTML = "";
	for (var mon of mons){
		if (!(mon.cr > cr)){
			var row = listOutput.insertRow(-1);
			var cell1 = row.insertCell(0);
			var cell2 = row.insertCell(1);
			cell1.innerHTML = mon.name;
			cell2.innerHTML = mon.cr;
		}
	}
}

var mons = [{id: "bulbasaur", name: "Bulbasaur", dex: 1, cr: 45},
{id: "ivysaur", name: "Ivysaur", dex: 2, cr: 45},
{id: "venusaur", name: "Venusaur", dex: 3, cr: 45},
{id: "charmander", name: "Charmander", dex: 4, cr: 45},
{id: "charmeleon", name: "Charmeleon", dex: 5, cr: 45},
{id: "charizard", name: "Charizard", dex: 6, cr: 45},
{id: "squirtle", name: "Squirtle", dex: 7, cr: 45},
{id: "wartortle", name: "Wartortle", dex: 8, cr: 45},
{id: "blastoise", name: "Blastoise", dex: 9, cr: 45},
{id: "caterpie", name: "Caterpie", dex: 10, cr: 255},
{id: "metapod", name: "Metapod", dex: 11, cr: 120},
{id: "butterfree", name: "Butterfree", dex: 12, cr: 45},
{id: "weedle", name: "Weedle", dex: 13, cr: 255},
{id: "kakuna", name: "Kakuna", dex: 14, cr: 120},
{id: "beedrill", name: "Beedrill", dex: 15, cr: 45},
{id: "pidgey", name: "Pidgey", dex: 16, cr: 255},
{id: "pidgeotto", name: "Pidgeotto", dex: 17, cr: 120},
{id: "pidgeot", name: "Pidgeot", dex: 18, cr: 45},
{id: "rattata", name: "Rattata", dex: 19, cr: 255},
{id: "raticate", name: "Raticate", dex: 20, cr: 127},
{id: "spearow", name: "Spearow", dex: 21, cr: 255},
{id: "fearow", name: "Fearow", dex: 22, cr: 90},
{id: "ekans", name: "Ekans", dex: 23, cr: 255},
{id: "arbok", name: "Arbok", dex: 24, cr: 90},
{id: "pikachu", name: "Pikachu", dex: 25, cr: 190},
{id: "raichu", name: "Raichu", dex: 26, cr: 75},
{id: "sandshrew", name: "Sandshrew", dex: 27, cr: 255},
{id: "sandslash", name: "Sandslash", dex: 28, cr: 90},
{id: "nidoranf", name: "Nidoran♀", dex: 29, cr: 235},
{id: "nidorina", name: "Nidorina", dex: 30, cr: 120},
{id: "nidoqueen", name: "Nidoqueen", dex: 31, cr: 45},
{id: "nidoranm", name: "Nidoran♂", dex: 32, cr: 235},
{id: "nidorino", name: "Nidorino", dex: 33, cr: 120},
{id: "nidoking", name: "Nidoking", dex: 34, cr: 45},
{id: "clefairy", name: "Clefairy", dex: 35, cr: 150},
{id: "clefable", name: "Clefable", dex: 36, cr: 25},
{id: "vulpix", name: "Vulpix", dex: 37, cr: 190},
{id: "ninetales", name: "Ninetales", dex: 38, cr: 75},
{id: "jigglypuff", name: "Jigglypuff", dex: 39, cr: 170},
{id: "wigglytuff", name: "Wigglytuff", dex: 40, cr: 50},
{id: "zubat", name: "Zubat", dex: 41, cr: 255},
{id: "golbat", name: "Golbat", dex: 42, cr: 90},
{id: "oddish", name: "Oddish", dex: 43, cr: 255},
{id: "gloom", name: "Gloom", dex: 44, cr: 120},
{id: "vileplume", name: "Vileplume", dex: 45, cr: 45},
{id: "paras", name: "Paras", dex: 46, cr: 190},
{id: "parasect", name: "Parasect", dex: 47, cr: 75},
{id: "venonat", name: "Venonat", dex: 48, cr: 190},
{id: "venomoth", name: "Venomoth", dex: 49, cr: 75},
{id: "diglett", name: "Diglett", dex: 50, cr: 255},
{id: "dugtrio", name: "Dugtrio", dex: 51, cr: 50},
{id: "meowth", name: "Meowth", dex: 52, cr: 255},
{id: "persian", name: "Persian", dex: 53, cr: 90},
{id: "psyduck", name: "Psyduck", dex: 54, cr: 190},
{id: "golduck", name: "Golduck", dex: 55, cr: 75},
{id: "mankey", name: "Mankey", dex: 56, cr: 190},
{id: "primeape", name: "Primeape", dex: 57, cr: 75},
{id: "growlithe", name: "Growlithe", dex: 58, cr: 190},
{id: "arcanine", name: "Arcanine", dex: 59, cr: 75},
{id: "poliwag", name: "Poliwag", dex: 60, cr: 255},
{id: "poliwhirl", name: "Poliwhirl", dex: 61, cr: 120},
{id: "poliwrath", name: "Poliwrath", dex: 62, cr: 45},
{id: "abra", name: "Abra", dex: 63, cr: 200},
{id: "kadabra", name: "Kadabra", dex: 64, cr: 100},
{id: "alakazam", name: "Alakazam", dex: 65, cr: 50},
{id: "machop", name: "Machop", dex: 66, cr: 180},
{id: "machoke", name: "Machoke", dex: 67, cr: 90},
{id: "machamp", name: "Machamp", dex: 68, cr: 45},
{id: "bellsprout", name: "Bellsprout", dex: 69, cr: 255},
{id: "weepinbell", name: "Weepinbell", dex: 70, cr: 120},
{id: "victreebel", name: "Victreebel", dex: 71, cr: 45},
{id: "tentacool", name: "Tentacool", dex: 72, cr: 190},
{id: "tentacruel", name: "Tentacruel", dex: 73, cr: 60},
{id: "geodude", name: "Geodude", dex: 74, cr: 255},
{id: "graveler", name: "Graveler", dex: 75, cr: 120},
{id: "golem", name: "Golem", dex: 76, cr: 45},
{id: "ponyta", name: "Ponyta", dex: 77, cr: 190},
{id: "rapidash", name: "Rapidash", dex: 78, cr: 60},
{id: "slowpoke", name: "Slowpoke", dex: 79, cr: 190},
{id: "slowbro", name: "Slowbro", dex: 80, cr: 75},
{id: "magnemite", name: "Magnemite", dex: 81, cr: 190},
{id: "magneton", name: "Magneton", dex: 82, cr: 60},
{id: "farfetch'd", name: "Farfetch'd", dex: 83, cr: 45},
{id: "doduo", name: "Doduo", dex: 84, cr: 190},
{id: "dodrio", name: "Dodrio", dex: 85, cr: 45},
{id: "seel", name: "Seel", dex: 86, cr: 190},
{id: "dewgong", name: "Dewgong", dex: 87, cr: 75},
{id: "grimer", name: "Grimer", dex: 88, cr: 190},
{id: "muk", name: "Muk", dex: 89, cr: 75},
{id: "shellder", name: "Shellder", dex: 90, cr: 190},
{id: "cloyster", name: "Cloyster", dex: 91, cr: 60},
{id: "gastly", name: "Gastly", dex: 92, cr: 190},
{id: "haunter", name: "Haunter", dex: 93, cr: 90},
{id: "gengar", name: "Gengar", dex: 94, cr: 45},
{id: "onix", name: "Onix", dex: 95, cr: 45},
{id: "drowzee", name: "Drowzee", dex: 96, cr: 190},
{id: "hypno", name: "Hypno", dex: 97, cr: 75},
{id: "krabby", name: "Krabby", dex: 98, cr: 225},
{id: "kingler", name: "Kingler", dex: 99, cr: 60},
{id: "voltorb", name: "Voltorb", dex: 100, cr: 190},
{id: "electrode", name: "Electrode", dex: 101, cr: 60},
{id: "exeggcute", name: "Exeggcute", dex: 102, cr: 90},
{id: "exeggutor", name: "Exeggutor", dex: 103, cr: 45},
{id: "cubone", name: "Cubone", dex: 104, cr: 190},
{id: "marowak", name: "Marowak", dex: 105, cr: 75},
{id: "hitmonlee", name: "Hitmonlee", dex: 106, cr: 45},
{id: "hitmonchan", name: "Hitmonchan", dex: 107, cr: 45},
{id: "lickitung", name: "Lickitung", dex: 108, cr: 45},
{id: "koffing", name: "Koffing", dex: 109, cr: 190},
{id: "weezing", name: "Weezing", dex: 110, cr: 60},
{id: "rhyhorn", name: "Rhyhorn", dex: 111, cr: 120},
{id: "rhydon", name: "Rhydon", dex: 112, cr: 60},
{id: "chansey", name: "Chansey", dex: 113, cr: 30},
{id: "tangela", name: "Tangela", dex: 114, cr: 45},
{id: "kangaskhan", name: "Kangaskhan", dex: 115, cr: 45},
{id: "horsea", name: "Horsea", dex: 116, cr: 225},
{id: "seadra", name: "Seadra", dex: 117, cr: 75},
{id: "goldeen", name: "Goldeen", dex: 118, cr: 225},
{id: "seaking", name: "Seaking", dex: 119, cr: 60},
{id: "staryu", name: "Staryu", dex: 120, cr: 225},
{id: "starmie", name: "Starmie", dex: 121, cr: 60},
{id: "mr mime", name: "Mr. Mime", dex: 122, cr: 45},
{id: "scyther", name: "Scyther", dex: 123, cr: 45},
{id: "jynx", name: "Jynx", dex: 124, cr: 45},
{id: "electabuzz", name: "Electabuzz", dex: 125, cr: 45},
{id: "magmar", name: "Magmar", dex: 126, cr: 45},
{id: "pinsir", name: "Pinsir", dex: 127, cr: 45},
{id: "tauros", name: "Tauros", dex: 128, cr: 45},
{id: "magikarp", name: "Magikarp", dex: 129, cr: 255},
{id: "gyarados", name: "Gyarados", dex: 130, cr: 45},
{id: "lapras", name: "Lapras", dex: 131, cr: 45},
{id: "ditto", name: "Ditto", dex: 132, cr: 35},
{id: "eevee", name: "Eevee", dex: 133, cr: 45},
{id: "vaporeon", name: "Vaporeon", dex: 134, cr: 45},
{id: "jolteon", name: "Jolteon", dex: 135, cr: 45},
{id: "flareon", name: "Flareon", dex: 136, cr: 45},
{id: "porygon", name: "Porygon", dex: 137, cr: 45},
{id: "omanyte", name: "Omanyte", dex: 138, cr: 45},
{id: "omastar", name: "Omastar", dex: 139, cr: 45},
{id: "kabuto", name: "Kabuto", dex: 140, cr: 45},
{id: "kabutops", name: "Kabutops", dex: 141, cr: 45},
{id: "aerodactyl", name: "Aerodactyl", dex: 142, cr: 45},
{id: "snorlax", name: "Snorlax", dex: 143, cr: 25},
{id: "articuno", name: "Articuno", dex: 144, cr: 3},
{id: "zapdos", name: "Zapdos", dex: 145, cr: 3},
{id: "moltres", name: "Moltres", dex: 146, cr: 3},
{id: "dratini", name: "Dratini", dex: 147, cr: 45},
{id: "dragonair", name: "Dragonair", dex: 148, cr: 45},
{id: "dragonite", name: "Dragonite", dex: 149, cr: 45},
{id: "mewtwo", name: "Mewtwo", dex: 150, cr: 3},
{id: "mew", name: "Mew", dex: 151, cr: 45},
{id: "chikorita", name: "Chikorita", dex: 152, cr: 45},
{id: "bayleef", name: "Bayleef", dex: 153, cr: 45},
{id: "meganium", name: "Meganium", dex: 154, cr: 45},
{id: "cyndaquil", name: "Cyndaquil", dex: 155, cr: 45},
{id: "quilava", name: "Quilava", dex: 156, cr: 45},
{id: "typhlosion", name: "Typhlosion", dex: 157, cr: 45},
{id: "totodile", name: "Totodile", dex: 158, cr: 45},
{id: "croconaw", name: "Croconaw", dex: 159, cr: 45},
{id: "feraligatr", name: "Feraligatr", dex: 160, cr: 45},
{id: "sentret", name: "Sentret", dex: 161, cr: 255},
{id: "furret", name: "Furret", dex: 162, cr: 90},
{id: "hoothoot", name: "Hoothoot", dex: 163, cr: 255},
{id: "noctowl", name: "Noctowl", dex: 164, cr: 90},
{id: "ledyba", name: "Ledyba", dex: 165, cr: 255},
{id: "ledian", name: "Ledian", dex: 166, cr: 90},
{id: "spinarak", name: "Spinarak", dex: 167, cr: 255},
{id: "ariados", name: "Ariados", dex: 168, cr: 90},
{id: "crobat", name: "Crobat", dex: 169, cr: 90},
{id: "chinchou", name: "Chinchou", dex: 170, cr: 190},
{id: "lanturn", name: "Lanturn", dex: 171, cr: 75},
{id: "pichu", name: "Pichu", dex: 172, cr: 190},
{id: "cleffa", name: "Cleffa", dex: 173, cr: 150},
{id: "igglybuff", name: "Igglybuff", dex: 174, cr: 170},
{id: "togepi", name: "Togepi", dex: 175, cr: 190},
{id: "togetic", name: "Togetic", dex: 176, cr: 75},
{id: "natu", name: "Natu", dex: 177, cr: 190},
{id: "xatu", name: "Xatu", dex: 178, cr: 75},
{id: "mareep", name: "Mareep", dex: 179, cr: 235},
{id: "flaaffy", name: "Flaaffy", dex: 180, cr: 120},
{id: "ampharos", name: "Ampharos", dex: 181, cr: 45},
{id: "bellossom", name: "Bellossom", dex: 182, cr: 45},
{id: "marill", name: "Marill", dex: 183, cr: 190},
{id: "azumarill", name: "Azumarill", dex: 184, cr: 75},
{id: "sudowoodo", name: "Sudowoodo", dex: 185, cr: 65},
{id: "politoed", name: "Politoed", dex: 186, cr: 45},
{id: "hoppip", name: "Hoppip", dex: 187, cr: 255},
{id: "skiploom", name: "Skiploom", dex: 188, cr: 120},
{id: "jumpluff", name: "Jumpluff", dex: 189, cr: 45},
{id: "aipom", name: "Aipom", dex: 190, cr: 45},
{id: "sunkern", name: "Sunkern", dex: 191, cr: 235},
{id: "sunflora", name: "Sunflora", dex: 192, cr: 120},
{id: "yanma", name: "Yanma", dex: 193, cr: 75},
{id: "wooper", name: "Wooper", dex: 194, cr: 255},
{id: "quagsire", name: "Quagsire", dex: 195, cr: 90},
{id: "espeon", name: "Espeon", dex: 196, cr: 45},
{id: "umbreon", name: "Umbreon", dex: 197, cr: 45},
{id: "murkrow", name: "Murkrow", dex: 198, cr: 30},
{id: "slowking", name: "Slowking", dex: 199, cr: 70},
{id: "misdreavus", name: "Misdreavus", dex: 200, cr: 45},
{id: "unown", name: "Unown", dex: 201, cr: 225},
{id: "wobbuffet", name: "Wobbuffet", dex: 202, cr: 45},
{id: "girafarig", name: "Girafarig", dex: 203, cr: 60},
{id: "pineco", name: "Pineco", dex: 204, cr: 190},
{id: "forretress", name: "Forretress", dex: 205, cr: 75},
{id: "dunsparce", name: "Dunsparce", dex: 206, cr: 190},
{id: "gligar", name: "Gligar", dex: 207, cr: 60},
{id: "steelix", name: "Steelix", dex: 208, cr: 25},
{id: "snubbull", name: "Snubbull", dex: 209, cr: 190},
{id: "granbull", name: "Granbull", dex: 210, cr: 75},
{id: "qwilfish", name: "Qwilfish", dex: 211, cr: 45},
{id: "scizor", name: "Scizor", dex: 212, cr: 25},
{id: "shuckle", name: "Shuckle", dex: 213, cr: 190},
{id: "heracross", name: "Heracross", dex: 214, cr: 45},
{id: "sneasel", name: "Sneasel", dex: 215, cr: 60},
{id: "teddiursa", name: "Teddiursa", dex: 216, cr: 120},
{id: "ursaring", name: "Ursaring", dex: 217, cr: 60},
{id: "slugma", name: "Slugma", dex: 218, cr: 190},
{id: "magcargo", name: "Magcargo", dex: 219, cr: 75},
{id: "swinub", name: "Swinub", dex: 220, cr: 225},
{id: "piloswine", name: "Piloswine", dex: 221, cr: 75},
{id: "corsola", name: "Corsola", dex: 222, cr: 60},
{id: "remoraid", name: "Remoraid", dex: 223, cr: 190},
{id: "octillery", name: "Octillery", dex: 224, cr: 75},
{id: "delibird", name: "Delibird", dex: 225, cr: 45},
{id: "mantine", name: "Mantine", dex: 226, cr: 25},
{id: "skarmory", name: "Skarmory", dex: 227, cr: 25},
{id: "houndour", name: "Houndour", dex: 228, cr: 120},
{id: "houndoom", name: "Houndoom", dex: 229, cr: 45},
{id: "kingdra", name: "Kingdra", dex: 230, cr: 45},
{id: "phanpy", name: "Phanpy", dex: 231, cr: 120},
{id: "donphan", name: "Donphan", dex: 232, cr: 60},
{id: "porygon2", name: "Porygon2", dex: 233, cr: 45},
{id: "stantler", name: "Stantler", dex: 234, cr: 45},
{id: "smeargle", name: "Smeargle", dex: 235, cr: 45},
{id: "tyrogue", name: "Tyrogue", dex: 236, cr: 75},
{id: "hitmontop", name: "Hitmontop", dex: 237, cr: 45},
{id: "smoochum", name: "Smoochum", dex: 238, cr: 45},
{id: "elekid", name: "Elekid", dex: 239, cr: 45},
{id: "magby", name: "Magby", dex: 240, cr: 45},
{id: "miltank", name: "Miltank", dex: 241, cr: 45},
{id: "blissey", name: "Blissey", dex: 242, cr: 30},
{id: "raikou", name: "Raikou", dex: 243, cr: 3},
{id: "entei", name: "Entei", dex: 244, cr: 3},
{id: "suicune", name: "Suicune", dex: 245, cr: 3},
{id: "larvitar", name: "Larvitar", dex: 246, cr: 45},
{id: "pupitar", name: "Pupitar", dex: 247, cr: 45},
{id: "tyranitar", name: "Tyranitar", dex: 248, cr: 45},
{id: "lugia", name: "Lugia", dex: 249, cr: 3},
{id: "ho-oh", name: "Ho-oh", dex: 250, cr: 3},
{id: "celebi", name: "Celebi", dex: 251, cr: 45},
{id: "treecko", name: "Treecko", dex: 252, cr: 45},
{id: "grovyle", name: "Grovyle", dex: 253, cr: 45},
{id: "sceptile", name: "Sceptile", dex: 254, cr: 45},
{id: "torchic", name: "Torchic", dex: 255, cr: 45},
{id: "combusken", name: "Combusken", dex: 256, cr: 45},
{id: "blaziken", name: "Blaziken", dex: 257, cr: 45},
{id: "mudkip", name: "Mudkip", dex: 258, cr: 45},
{id: "marshtomp", name: "Marshtomp", dex: 259, cr: 45},
{id: "swampert", name: "Swampert", dex: 260, cr: 45},
{id: "poochyena", name: "Poochyena", dex: 261, cr: 255},
{id: "mightyena", name: "Mightyena", dex: 262, cr: 127},
{id: "zigzagoon", name: "Zigzagoon", dex: 263, cr: 255},
{id: "linoone", name: "Linoone", dex: 264, cr: 90},
{id: "wurmple", name: "Wurmple", dex: 265, cr: 255},
{id: "silcoon", name: "Silcoon", dex: 266, cr: 120},
{id: "beautifly", name: "Beautifly", dex: 267, cr: 45},
{id: "cascoon", name: "Cascoon", dex: 268, cr: 120},
{id: "dustox", name: "Dustox", dex: 269, cr: 45},
{id: "lotad", name: "Lotad", dex: 270, cr: 255},
{id: "lombre", name: "Lombre", dex: 271, cr: 120},
{id: "ludicolo", name: "Ludicolo", dex: 272, cr: 45},
{id: "seedot", name: "Seedot", dex: 273, cr: 255},
{id: "nuzleaf", name: "Nuzleaf", dex: 274, cr: 120},
{id: "shiftry", name: "Shiftry", dex: 275, cr: 45},
{id: "taillow", name: "Taillow", dex: 276, cr: 200},
{id: "swellow", name: "Swellow", dex: 277, cr: 45},
{id: "wingull", name: "Wingull", dex: 278, cr: 190},
{id: "pelipper", name: "Pelipper", dex: 279, cr: 45},
{id: "ralts", name: "Ralts", dex: 280, cr: 235},
{id: "kirlia", name: "Kirlia", dex: 281, cr: 120},
{id: "gardevoir", name: "Gardevoir", dex: 282, cr: 45},
{id: "surskit", name: "Surskit", dex: 283, cr: 200},
{id: "masquerain", name: "Masquerain", dex: 284, cr: 75},
{id: "shroomish", name: "Shroomish", dex: 285, cr: 255},
{id: "breloom", name: "Breloom", dex: 286, cr: 90},
{id: "slakoth", name: "Slakoth", dex: 287, cr: 255},
{id: "vigoroth", name: "Vigoroth", dex: 288, cr: 120},
{id: "slaking", name: "Slaking", dex: 289, cr: 45},
{id: "nincada", name: "Nincada", dex: 290, cr: 255},
{id: "ninjask", name: "Ninjask", dex: 291, cr: 120},
{id: "shedinja", name: "Shedinja", dex: 292, cr: 45},
{id: "whismur", name: "Whismur", dex: 293, cr: 190},
{id: "loudred", name: "Loudred", dex: 294, cr: 120},
{id: "exploud", name: "Exploud", dex: 295, cr: 45},
{id: "makuhita", name: "Makuhita", dex: 296, cr: 180},
{id: "hariyama", name: "Hariyama", dex: 297, cr: 200},
{id: "azurill", name: "Azurill", dex: 298, cr: 150},
{id: "nosepass", name: "Nosepass", dex: 299, cr: 255},
{id: "skitty", name: "Skitty", dex: 300, cr: 255},
{id: "delcatty", name: "Delcatty", dex: 301, cr: 60},
{id: "sableye", name: "Sableye", dex: 302, cr: 45},
{id: "mawile", name: "Mawile", dex: 303, cr: 45},
{id: "aron", name: "Aron", dex: 304, cr: 180},
{id: "lairon", name: "Lairon", dex: 305, cr: 90},
{id: "aggron", name: "Aggron", dex: 306, cr: 45},
{id: "meditite", name: "Meditite", dex: 307, cr: 180},
{id: "medicham", name: "Medicham", dex: 308, cr: 90},
{id: "electrike", name: "Electrike", dex: 309, cr: 120},
{id: "manectric", name: "Manectric", dex: 310, cr: 45},
{id: "plusle", name: "Plusle", dex: 311, cr: 200},
{id: "minun", name: "Minun", dex: 312, cr: 200},
{id: "volbeat", name: "Volbeat", dex: 313, cr: 150},
{id: "illumise", name: "Illumise", dex: 314, cr: 150},
{id: "roselia", name: "Roselia", dex: 315, cr: 150},
{id: "gulpin", name: "Gulpin", dex: 316, cr: 225},
{id: "swalot", name: "Swalot", dex: 317, cr: 75},
{id: "carvanha", name: "Carvanha", dex: 318, cr: 225},
{id: "sharpedo", name: "Sharpedo", dex: 319, cr: 60},
{id: "wailmer", name: "Wailmer", dex: 320, cr: 125},
{id: "wailord", name: "Wailord", dex: 321, cr: 60},
{id: "numel", name: "Numel", dex: 322, cr: 255},
{id: "camerupt", name: "Camerupt", dex: 323, cr: 150},
{id: "torkoal", name: "Torkoal", dex: 324, cr: 90},
{id: "spoink", name: "Spoink", dex: 325, cr: 255},
{id: "grumpig", name: "Grumpig", dex: 326, cr: 60},
{id: "spinda", name: "Spinda", dex: 327, cr: 255},
{id: "trapinch", name: "Trapinch", dex: 328, cr: 255},
{id: "vibrava", name: "Vibrava", dex: 329, cr: 120},
{id: "flygon", name: "Flygon", dex: 330, cr: 45},
{id: "cacnea", name: "Cacnea", dex: 331, cr: 190},
{id: "cacturne", name: "Cacturne", dex: 332, cr: 60},
{id: "swablu", name: "Swablu", dex: 333, cr: 255},
{id: "altaria", name: "Altaria", dex: 334, cr: 45},
{id: "zangoose", name: "Zangoose", dex: 335, cr: 90},
{id: "seviper", name: "Seviper", dex: 336, cr: 90},
{id: "lunatone", name: "Lunatone", dex: 337, cr: 45},
{id: "solrock", name: "Solrock", dex: 338, cr: 45},
{id: "barboach", name: "Barboach", dex: 339, cr: 190},
{id: "whiscash", name: "Whiscash", dex: 340, cr: 75},
{id: "corphish", name: "Corphish", dex: 341, cr: 205},
{id: "crawdaunt", name: "Crawdaunt", dex: 342, cr: 155},
{id: "baltoy", name: "Baltoy", dex: 343, cr: 255},
{id: "claydol", name: "Claydol", dex: 344, cr: 90},
{id: "lileep", name: "Lileep", dex: 345, cr: 45},
{id: "cradily", name: "Cradily", dex: 346, cr: 45},
{id: "anorith", name: "Anorith", dex: 347, cr: 45},
{id: "armaldo", name: "Armaldo", dex: 348, cr: 45},
{id: "feebas", name: "Feebas", dex: 349, cr: 255},
{id: "milotic", name: "Milotic", dex: 350, cr: 60},
{id: "castform", name: "Castform", dex: 351, cr: 45},
{id: "kecleon", name: "Kecleon", dex: 352, cr: 200},
{id: "shuppet", name: "Shuppet", dex: 353, cr: 225},
{id: "banette", name: "Banette", dex: 354, cr: 45},
{id: "duskull", name: "Duskull", dex: 355, cr: 190},
{id: "dusclops", name: "Dusclops", dex: 356, cr: 90},
{id: "tropius", name: "Tropius", dex: 357, cr: 200},
{id: "chimecho", name: "Chimecho", dex: 358, cr: 45},
{id: "absol", name: "Absol", dex: 359, cr: 30},
{id: "wynaut", name: "Wynaut", dex: 360, cr: 125},
{id: "snorunt", name: "Snorunt", dex: 361, cr: 190},
{id: "glalie", name: "Glalie", dex: 362, cr: 75},
{id: "spheal", name: "Spheal", dex: 363, cr: 255},
{id: "sealeo", name: "Sealeo", dex: 364, cr: 120},
{id: "walrein", name: "Walrein", dex: 365, cr: 45},
{id: "clamperl", name: "Clamperl", dex: 366, cr: 255},
{id: "huntail", name: "Huntail", dex: 367, cr: 60},
{id: "gorebyss", name: "Gorebyss", dex: 368, cr: 60},
{id: "relicanth", name: "Relicanth", dex: 369, cr: 25},
{id: "luvdisc", name: "Luvdisc", dex: 370, cr: 225},
{id: "bagon", name: "Bagon", dex: 371, cr: 45},
{id: "shelgon", name: "Shelgon", dex: 372, cr: 45},
{id: "salamence", name: "Salamence", dex: 373, cr: 45},
{id: "beldum", name: "Beldum", dex: 374, cr: 3},
{id: "metang", name: "Metang", dex: 375, cr: 3},
{id: "metagross", name: "Metagross", dex: 376, cr: 3},
{id: "regirock", name: "Regirock", dex: 377, cr: 3},
{id: "regice", name: "Regice", dex: 378, cr: 3},
{id: "registeel", name: "Registeel", dex: 379, cr: 3},
{id: "latias", name: "Latias", dex: 380, cr: 3},
{id: "latios", name: "Latios", dex: 381, cr: 3},
{id: "kyogre", name: "Kyogre", dex: 382, cr: 3},
{id: "groudon", name: "Groudon", dex: 383, cr: 3},
{id: "rayquaza", name: "Rayquaza", dex: 384, cr: 45},
{id: "jirachi", name: "Jirachi", dex: 385, cr: 3},
{id: "deoxys", name: "Deoxys", dex: 386, cr: 3},
{id: "turtwig", name: "Turtwig", dex: 387, cr: 45},
{id: "grotle", name: "Grotle", dex: 388, cr: 45},
{id: "torterra", name: "Torterra", dex: 389, cr: 45},
{id: "chimchar", name: "Chimchar", dex: 390, cr: 45},
{id: "monferno", name: "Monferno", dex: 391, cr: 45},
{id: "infernape", name: "Infernape", dex: 392, cr: 45},
{id: "piplup", name: "Piplup", dex: 393, cr: 45},
{id: "prinplup", name: "Prinplup", dex: 394, cr: 45},
{id: "empoleon", name: "Empoleon", dex: 395, cr: 45},
{id: "starly", name: "Starly", dex: 396, cr: 255},
{id: "staravia", name: "Staravia", dex: 397, cr: 120},
{id: "staraptor", name: "Staraptor", dex: 398, cr: 45},
{id: "bidoof", name: "Bidoof", dex: 399, cr: 255},
{id: "bibarel", name: "Bibarel", dex: 400, cr: 127},
{id: "kricketot", name: "Kricketot", dex: 401, cr: 255},
{id: "kricketune", name: "Kricketune", dex: 402, cr: 45},
{id: "shinx", name: "Shinx", dex: 403, cr: 235},
{id: "luxio", name: "Luxio", dex: 404, cr: 120},
{id: "luxray", name: "Luxray", dex: 405, cr: 45},
{id: "budew", name: "Budew", dex: 406, cr: 255},
{id: "roserade", name: "Roserade", dex: 407, cr: 75},
{id: "cranidos", name: "Cranidos", dex: 408, cr: 45},
{id: "rampardos", name: "Rampardos", dex: 409, cr: 45},
{id: "shieldon", name: "Shieldon", dex: 410, cr: 45},
{id: "bastiodon", name: "Bastiodon", dex: 411, cr: 45},
{id: "burmy", name: "Burmy", dex: 412, cr: 120},
{id: "wormadam", name: "Wormadam", dex: 413, cr: 45},
{id: "mothim", name: "Mothim", dex: 414, cr: 45},
{id: "combee", name: "Combee", dex: 415, cr: 120},
{id: "vespiquen", name: "Vespiquen", dex: 416, cr: 45},
{id: "pachirisu", name: "Pachirisu", dex: 417, cr: 200},
{id: "buizel", name: "Buizel", dex: 418, cr: 190},
{id: "floatzel", name: "Floatzel", dex: 419, cr: 75},
{id: "cherubi", name: "Cherubi", dex: 420, cr: 190},
{id: "cherrim", name: "Cherrim", dex: 421, cr: 75},
{id: "shellos", name: "Shellos", dex: 422, cr: 190},
{id: "gastrodon", name: "Gastrodon", dex: 423, cr: 75},
{id: "ambipom", name: "Ambipom", dex: 424, cr: 45},
{id: "drifloon", name: "Drifloon", dex: 425, cr: 125},
{id: "drifblim", name: "Drifblim", dex: 426, cr: 60},
{id: "buneary", name: "Buneary", dex: 427, cr: 190},
{id: "lopunny", name: "Lopunny", dex: 428, cr: 60},
{id: "mismagius", name: "Mismagius", dex: 429, cr: 45},
{id: "honchkrow", name: "Honchkrow", dex: 430, cr: 30},
{id: "glameow", name: "Glameow", dex: 431, cr: 190},
{id: "purugly", name: "Purugly", dex: 432, cr: 75},
{id: "chingling", name: "Chingling", dex: 433, cr: 120},
{id: "stunky", name: "Stunky", dex: 434, cr: 225},
{id: "skuntank", name: "Skuntank", dex: 435, cr: 60},
{id: "bronzor", name: "Bronzor", dex: 436, cr: 255},
{id: "bronzong", name: "Bronzong", dex: 437, cr: 90},
{id: "bonsly", name: "Bonsly", dex: 438, cr: 255},
{id: "mime jr", name: "Mime Jr.", dex: 439, cr: 145},
{id: "happiny", name: "Happiny", dex: 440, cr: 130},
{id: "chatot", name: "Chatot", dex: 441, cr: 30},
{id: "spiritomb", name: "Spiritomb", dex: 442, cr: 100},
{id: "gible", name: "Gible", dex: 443, cr: 45},
{id: "gabite", name: "Gabite", dex: 444, cr: 45},
{id: "garchomp", name: "Garchomp", dex: 445, cr: 45},
{id: "munchlax", name: "Munchlax", dex: 446, cr: 50},
{id: "riolu", name: "Riolu", dex: 447, cr: 75},
{id: "lucario", name: "Lucario", dex: 448, cr: 45},
{id: "hippopotas", name: "Hippopotas", dex: 449, cr: 140},
{id: "hippowdon", name: "Hippowdon", dex: 450, cr: 60},
{id: "skorupi", name: "Skorupi", dex: 451, cr: 120},
{id: "drapion", name: "Drapion", dex: 452, cr: 45},
{id: "croagunk", name: "Croagunk", dex: 453, cr: 140},
{id: "toxicroak", name: "Toxicroak", dex: 454, cr: 75},
{id: "carnivine", name: "Carnivine", dex: 455, cr: 200},
{id: "finneon", name: "Finneon", dex: 456, cr: 190},
{id: "lumineon", name: "Lumineon", dex: 457, cr: 75},
{id: "mantyke", name: "Mantyke", dex: 458, cr: 25},
{id: "snover", name: "Snover", dex: 459, cr: 120},
{id: "abomasnow", name: "Abomasnow", dex: 460, cr: 60},
{id: "weavile", name: "Weavile", dex: 461, cr: 45},
{id: "magnezone", name: "Magnezone", dex: 462, cr: 30},
{id: "lickilicky", name: "Lickilicky", dex: 463, cr: 30},
{id: "rhyperior", name: "Rhyperior", dex: 464, cr: 30},
{id: "tangrowth", name: "Tangrowth", dex: 465, cr: 30},
{id: "electivire", name: "Electivire", dex: 466, cr: 30},
{id: "magmortar", name: "Magmortar", dex: 467, cr: 30},
{id: "togekiss", name: "Togekiss", dex: 468, cr: 30},
{id: "yanmega", name: "Yanmega", dex: 469, cr: 30},
{id: "leafeon", name: "Leafeon", dex: 470, cr: 45},
{id: "glaceon", name: "Glaceon", dex: 471, cr: 45},
{id: "gliscor", name: "Gliscor", dex: 472, cr: 30},
{id: "mamoswine", name: "Mamoswine", dex: 473, cr: 50},
{id: "porygon z", name: "Porygon-Z", dex: 474, cr: 30},
{id: "gallade", name: "Gallade", dex: 475, cr: 45},
{id: "probopass", name: "Probopass", dex: 476, cr: 60},
{id: "dusknoir", name: "Dusknoir", dex: 477, cr: 45},
{id: "froslass", name: "Froslass", dex: 478, cr: 75},
{id: "rotom", name: "Rotom", dex: 479, cr: 45},
{id: "uxie", name: "Uxie", dex: 480, cr: 3},
{id: "mesprit", name: "Mesprit", dex: 481, cr: 3},
{id: "azelf", name: "Azelf", dex: 482, cr: 3},
{id: "dialga", name: "Dialga", dex: 483, cr: 3},
{id: "palkia", name: "Palkia", dex: 484, cr: 3},
{id: "heatran", name: "Heatran", dex: 485, cr: 3},
{id: "regigigas", name: "Regigigas", dex: 486, cr: 3},
{id: "giratina", name: "Giratina", dex: 487, cr: 3},
{id: "cresselia", name: "Cresselia", dex: 488, cr: 3},
{id: "phione", name: "Phione", dex: 489, cr: 30},
{id: "manaphy", name: "Manaphy", dex: 490, cr: 3},
{id: "darkrai", name: "Darkrai", dex: 491, cr: 3},
{id: "shaymin", name: "Shaymin", dex: 492, cr: 45},
{id: "arceus", name: "Arceus", dex: 493, cr: 3},
{id: "victini", name: "Victini", dex: 494, cr: 3},
{id: "snivy", name: "Snivy", dex: 495, cr: 45},
{id: "servine", name: "Servine", dex: 496, cr: 45},
{id: "serperior", name: "Serperior", dex: 497, cr: 45},
{id: "tepig", name: "Tepig", dex: 498, cr: 45},
{id: "pignite", name: "Pignite", dex: 499, cr: 45},
{id: "emboar", name: "Emboar", dex: 500, cr: 45},
{id: "oshawott", name: "Oshawott", dex: 501, cr: 45},
{id: "dewott", name: "Dewott", dex: 502, cr: 45},
{id: "samurott", name: "Samurott", dex: 503, cr: 45},
{id: "patrat", name: "Patrat", dex: 504, cr: 255},
{id: "watchog", name: "Watchog", dex: 505, cr: 255},
{id: "lillipup", name: "Lillipup", dex: 506, cr: 255},
{id: "herdier", name: "Herdier", dex: 507, cr: 120},
{id: "stoutland", name: "Stoutland", dex: 508, cr: 45},
{id: "purrloin", name: "Purrloin", dex: 509, cr: 255},
{id: "liepard", name: "Liepard", dex: 510, cr: 90},
{id: "pansage", name: "Pansage", dex: 511, cr: 190},
{id: "simisage", name: "Simisage", dex: 512, cr: 75},
{id: "pansear", name: "Pansear", dex: 513, cr: 190},
{id: "simisear", name: "Simisear", dex: 514, cr: 75},
{id: "panpour", name: "Panpour", dex: 515, cr: 190},
{id: "simipour", name: "Simipour", dex: 516, cr: 75},
{id: "munna", name: "Munna", dex: 517, cr: 190},
{id: "musharna", name: "Musharna", dex: 518, cr: 75},
{id: "pidove", name: "Pidove", dex: 519, cr: 255},
{id: "tranquill", name: "Tranquill", dex: 520, cr: 120},
{id: "unfezant", name: "Unfezant", dex: 521, cr: 45},
{id: "blitzle", name: "Blitzle", dex: 522, cr: 190},
{id: "zebstrika", name: "Zebstrika", dex: 523, cr: 75},
{id: "roggenrola", name: "Roggenrola", dex: 524, cr: 255},
{id: "boldore", name: "Boldore", dex: 525, cr: 120},
{id: "gigalith", name: "Gigalith", dex: 526, cr: 45},
{id: "woobat", name: "Woobat", dex: 527, cr: 190},
{id: "swoobat", name: "Swoobat", dex: 528, cr: 45},
{id: "drilbur", name: "Drilbur", dex: 529, cr: 120},
{id: "excadrill", name: "Excadrill", dex: 530, cr: 60},
{id: "audino", name: "Audino", dex: 531, cr: 255},
{id: "timburr", name: "Timburr", dex: 532, cr: 180},
{id: "gurdurr", name: "Gurdurr", dex: 533, cr: 90},
{id: "conkeldurr", name: "Conkeldurr", dex: 534, cr: 45},
{id: "tympole", name: "Tympole", dex: 535, cr: 255},
{id: "palpitoad", name: "Palpitoad", dex: 536, cr: 120},
{id: "seismitoad", name: "Seismitoad", dex: 537, cr: 45},
{id: "throh", name: "Throh", dex: 538, cr: 45},
{id: "sawk", name: "Sawk", dex: 539, cr: 45},
{id: "sewaddle", name: "Sewaddle", dex: 540, cr: 255},
{id: "swadloon", name: "Swadloon", dex: 541, cr: 120},
{id: "leavanny", name: "Leavanny", dex: 542, cr: 45},
{id: "venipede", name: "Venipede", dex: 543, cr: 255},
{id: "whirlipede", name: "Whirlipede", dex: 544, cr: 120},
{id: "scolipede", name: "Scolipede", dex: 545, cr: 45},
{id: "cottonee", name: "Cottonee", dex: 546, cr: 190},
{id: "whimsicott", name: "Whimsicott", dex: 547, cr: 75},
{id: "petilil", name: "Petilil", dex: 548, cr: 190},
{id: "lilligant", name: "Lilligant", dex: 549, cr: 75},
{id: "basculin", name: "Basculin", dex: 550, cr: 25},
{id: "sandile", name: "Sandile", dex: 551, cr: 180},
{id: "krokorok", name: "Krokorok", dex: 552, cr: 90},
{id: "krookodile", name: "Krookodile", dex: 553, cr: 45},
{id: "darumaka", name: "Darumaka", dex: 554, cr: 120},
{id: "darmanitan", name: "Darmanitan", dex: 555, cr: 60},
{id: "maractus", name: "Maractus", dex: 556, cr: 255},
{id: "dwebble", name: "Dwebble", dex: 557, cr: 190},
{id: "crustle", name: "Crustle", dex: 558, cr: 75},
{id: "scraggy", name: "Scraggy", dex: 559, cr: 180},
{id: "scrafty", name: "Scrafty", dex: 560, cr: 90},
{id: "sigilyph", name: "Sigilyph", dex: 561, cr: 45},
{id: "yamask", name: "Yamask", dex: 562, cr: 190},
{id: "cofagrigus", name: "Cofagrigus", dex: 563, cr: 90},
{id: "tirtouga", name: "Tirtouga", dex: 564, cr: 45},
{id: "carracosta", name: "Carracosta", dex: 565, cr: 45},
{id: "archen", name: "Archen", dex: 566, cr: 45},
{id: "archeops", name: "Archeops", dex: 567, cr: 45},
{id: "trubbish", name: "Trubbish", dex: 568, cr: 190},
{id: "garbodor", name: "Garbodor", dex: 569, cr: 60},
{id: "zorua", name: "Zorua", dex: 570, cr: 75},
{id: "zoroark", name: "Zoroark", dex: 571, cr: 45},
{id: "minccino", name: "Minccino", dex: 572, cr: 255},
{id: "cinccino", name: "Cinccino", dex: 573, cr: 60},
{id: "gothita", name: "Gothita", dex: 574, cr: 200},
{id: "gothorita", name: "Gothorita", dex: 575, cr: 100},
{id: "gothitelle", name: "Gothitelle", dex: 576, cr: 50},
{id: "solosis", name: "Solosis", dex: 577, cr: 200},
{id: "duosion", name: "Duosion", dex: 578, cr: 100},
{id: "reuniclus", name: "Reuniclus", dex: 579, cr: 50},
{id: "ducklett", name: "Ducklett", dex: 580, cr: 190},
{id: "swanna", name: "Swanna", dex: 581, cr: 45},
{id: "vanillite", name: "Vanillite", dex: 582, cr: 255},
{id: "vanillish", name: "Vanillish", dex: 583, cr: 120},
{id: "vanilluxe", name: "Vanilluxe", dex: 584, cr: 45},
{id: "deerling", name: "Deerling", dex: 585, cr: 190},
{id: "sawsbuck", name: "Sawsbuck", dex: 586, cr: 75},
{id: "emolga", name: "Emolga", dex: 587, cr: 200},
{id: "karrablast", name: "Karrablast", dex: 588, cr: 200},
{id: "escavalier", name: "Escavalier", dex: 589, cr: 75},
{id: "foongus", name: "Foongus", dex: 590, cr: 190},
{id: "amoonguss", name: "Amoonguss", dex: 591, cr: 75},
{id: "frillish", name: "Frillish", dex: 592, cr: 190},
{id: "jellicent", name: "Jellicent", dex: 593, cr: 60},
{id: "alomomola", name: "Alomomola", dex: 594, cr: 75},
{id: "joltik", name: "Joltik", dex: 595, cr: 190},
{id: "galvantula", name: "Galvantula", dex: 596, cr: 75},
{id: "ferroseed", name: "Ferroseed", dex: 597, cr: 255},
{id: "ferrothorn", name: "Ferrothorn", dex: 598, cr: 90},
{id: "klink", name: "Klink", dex: 599, cr: 130},
{id: "klang", name: "Klang", dex: 600, cr: 60},
{id: "klinklang", name: "Klinklang", dex: 601, cr: 30},
{id: "tynamo", name: "Tynamo", dex: 602, cr: 190},
{id: "eelektrik", name: "Eelektrik", dex: 603, cr: 60},
{id: "eelektross", name: "Eelektross", dex: 604, cr: 30},
{id: "elgyem", name: "Elgyem", dex: 605, cr: 255},
{id: "beheeyem", name: "Beheeyem", dex: 606, cr: 90},
{id: "litwick", name: "Litwick", dex: 607, cr: 190},
{id: "lampent", name: "Lampent", dex: 608, cr: 90},
{id: "chandelure", name: "Chandelure", dex: 609, cr: 45},
{id: "axew", name: "Axew", dex: 610, cr: 75},
{id: "fraxure", name: "Fraxure", dex: 611, cr: 60},
{id: "haxorus", name: "Haxorus", dex: 612, cr: 45},
{id: "cubchoo", name: "Cubchoo", dex: 613, cr: 120},
{id: "beartic", name: "Beartic", dex: 614, cr: 60},
{id: "cryogonal", name: "Cryogonal", dex: 615, cr: 25},
{id: "shelmet", name: "Shelmet", dex: 616, cr: 200},
{id: "accelgor", name: "Accelgor", dex: 617, cr: 75},
{id: "stunfisk", name: "Stunfisk", dex: 618, cr: 75},
{id: "mienfoo", name: "Mienfoo", dex: 619, cr: 180},
{id: "mienshao", name: "Mienshao", dex: 620, cr: 45},
{id: "druddigon", name: "Druddigon", dex: 621, cr: 45},
{id: "golett", name: "Golett", dex: 622, cr: 190},
{id: "golurk", name: "Golurk", dex: 623, cr: 90},
{id: "pawniard", name: "Pawniard", dex: 624, cr: 120},
{id: "bisharp", name: "Bisharp", dex: 625, cr: 45},
{id: "bouffalant", name: "Bouffalant", dex: 626, cr: 45},
{id: "rufflet", name: "Rufflet", dex: 627, cr: 190},
{id: "braviary", name: "Braviary", dex: 628, cr: 60},
{id: "vullaby", name: "Vullaby", dex: 629, cr: 190},
{id: "mandibuzz", name: "Mandibuzz", dex: 630, cr: 60},
{id: "heatmor", name: "Heatmor", dex: 631, cr: 90},
{id: "durant", name: "Durant", dex: 632, cr: 90},
{id: "deino", name: "Deino", dex: 633, cr: 45},
{id: "zweilous", name: "Zweilous", dex: 634, cr: 45},
{id: "hydreigon", name: "Hydreigon", dex: 635, cr: 45},
{id: "larvesta", name: "Larvesta", dex: 636, cr: 45},
{id: "volcarona", name: "Volcarona", dex: 637, cr: 15},
{id: "cobalion", name: "Cobalion", dex: 638, cr: 3},
{id: "terrakion", name: "Terrakion", dex: 639, cr: 3},
{id: "virizion", name: "Virizion", dex: 640, cr: 3},
{id: "tornadus", name: "Tornadus", dex: 641, cr: 3},
{id: "thundurus", name: "Thundurus", dex: 642, cr: 3},
{id: "reshiram", name: "Reshiram", dex: 643, cr: 3},
{id: "zekrom", name: "Zekrom", dex: 644, cr: 3},
{id: "landorus", name: "Landorus", dex: 645, cr: 3},
{id: "kyurem", name: "Kyurem", dex: 646, cr: 3},
{id: "keldeo", name: "Keldeo", dex: 647, cr: 3},
{id: "meloetta", name: "Meloetta", dex: 648, cr: 3},
{id: "genesect", name: "Genesect", dex: 649, cr: 3},
{id: "chespin", name: "Chespin", dex: 650, cr: 45},
{id: "quilladin", name: "Quilladin", dex: 651, cr: 45},
{id: "chesnaught", name: "Chesnaught", dex: 652, cr: 45},
{id: "fennekin", name: "Fennekin", dex: 653, cr: 45},
{id: "braixen", name: "Braixen", dex: 654, cr: 45},
{id: "delphox", name: "Delphox", dex: 655, cr: 45},
{id: "froakie", name: "Froakie", dex: 656, cr: 45},
{id: "frogadier", name: "Frogadier", dex: 657, cr: 45},
{id: "greninja", name: "Greninja", dex: 658, cr: 45},
{id: "bunnelby", name: "Bunnelby", dex: 659, cr: 255},
{id: "diggersby", name: "Diggersby", dex: 660, cr: 127},
{id: "fletchling", name: "Fletchling", dex: 661, cr: 255},
{id: "fletchinder", name: "Fletchinder", dex: 662, cr: 120},
{id: "talonflame", name: "Talonflame", dex: 663, cr: 45},
{id: "scatterbug", name: "Scatterbug", dex: 664, cr: 255},
{id: "spewpa", name: "Spewpa", dex: 665, cr: 120},
{id: "vivillon", name: "Vivillon", dex: 666, cr: 45},
{id: "litleo", name: "Litleo", dex: 667, cr: 220},
{id: "pyroar", name: "Pyroar", dex: 668, cr: 65},
{id: "flabebe", name: "Flabébé", dex: 669, cr: 225},
{id: "floette", name: "Floette", dex: 670, cr: 120},
{id: "florges", name: "Florges", dex: 671, cr: 45},
{id: "skiddo", name: "Skiddo", dex: 672, cr: 200},
{id: "gogoat", name: "Gogoat", dex: 673, cr: 45},
{id: "pancham", name: "Pancham", dex: 674, cr: 220},
{id: "pangoro", name: "Pangoro", dex: 675, cr: 65},
{id: "furfrou", name: "Furfrou", dex: 676, cr: 160},
{id: "espurr", name: "Espurr", dex: 677, cr: 190},
{id: "meowstic", name: "Meowstic", dex: 678, cr: 75},
{id: "honedge", name: "Honedge", dex: 679, cr: 180},
{id: "doublade", name: "Doublade", dex: 680, cr: 90},
{id: "aegislash", name: "Aegislash", dex: 681, cr: 45},
{id: "spritzee", name: "Spritzee", dex: 682, cr: 200},
{id: "aromatisse", name: "Aromatisse", dex: 683, cr: 140},
{id: "swirlix", name: "Swirlix", dex: 684, cr: 200},
{id: "slurpuff", name: "Slurpuff", dex: 685, cr: 140},
{id: "inkay", name: "Inkay", dex: 686, cr: 190},
{id: "malamar", name: "Malamar", dex: 687, cr: 80},
{id: "binacle", name: "Binacle", dex: 688, cr: 120},
{id: "barbaracle", name: "Barbaracle", dex: 689, cr: 45},
{id: "skrelp", name: "Skrelp", dex: 690, cr: 225},
{id: "dragalge", name: "Dragalge", dex: 691, cr: 55},
{id: "clauncher", name: "Clauncher", dex: 692, cr: 225},
{id: "clawitzer", name: "Clawitzer", dex: 693, cr: 55},
{id: "helioptile", name: "Helioptile", dex: 694, cr: 190},
{id: "heliolisk", name: "Heliolisk", dex: 695, cr: 75},
{id: "tyrunt", name: "Tyrunt", dex: 696, cr: 45},
{id: "tyrantrum", name: "Tyrantrum", dex: 697, cr: 45},
{id: "amaura", name: "Amaura", dex: 698, cr: 45},
{id: "aurorus", name: "Aurorus", dex: 699, cr: 45},
{id: "sylveon", name: "Sylveon", dex: 700, cr: 45},
{id: "hawlucha", name: "Hawlucha", dex: 701, cr: 100},
{id: "dedenne", name: "Dedenne", dex: 702, cr: 180},
{id: "carbink", name: "Carbink", dex: 703, cr: 60},
{id: "goomy", name: "Goomy", dex: 704, cr: 45},
{id: "sliggoo", name: "Sliggoo", dex: 705, cr: 45},
{id: "goodra", name: "Goodra", dex: 706, cr: 45},
{id: "klefki", name: "Klefki", dex: 707, cr: 75},
{id: "phantump", name: "Phantump", dex: 708, cr: 120},
{id: "trevenant", name: "Trevenant", dex: 709, cr: 60},
{id: "pumpkaboo", name: "Pumpkaboo", dex: 710, cr: 120},
{id: "gourgeist", name: "Gourgeist", dex: 711, cr: 60},
{id: "bergmite", name: "Bergmite", dex: 712, cr: 190},
{id: "avalugg", name: "Avalugg", dex: 713, cr: 55},
{id: "noibat", name: "Noibat", dex: 714, cr: 190},
{id: "noivern", name: "Noivern", dex: 715, cr: 45},
{id: "xerneas", name: "Xerneas", dex: 716, cr: 45},
{id: "yveltal", name: "Yveltal", dex: 717, cr: 45},
{id: "zygarde", name: "Zygarde", dex: 718, cr: 3},
{id: "diancie", name: "Diancie", dex: 719, cr: 3},
{id: "hoopa", name: "Hoopa", dex: 720, cr: 3},
{id: "volcanion", name: "Volcanion", dex: 721, cr: 3},
{id: "rowlet", name: "Rowlet", dex: 722, cr: 45},
{id: "dartrix", name: "Dartrix", dex: 723, cr: 45},
{id: "decidueye", name: "Decidueye", dex: 724, cr: 45},
{id: "litten", name: "Litten", dex: 725, cr: 45},
{id: "torracat", name: "Torracat", dex: 726, cr: 45},
{id: "incineroar", name: "Incineroar", dex: 727, cr: 45},
{id: "popplio", name: "Popplio", dex: 728, cr: 45},
{id: "brionne", name: "Brionne", dex: 729, cr: 45},
{id: "primarina", name: "Primarina", dex: 730, cr: 45},
{id: "pikipek", name: "Pikipek", dex: 731, cr: 255},
{id: "trumbeak", name: "Trumbeak", dex: 732, cr: 120},
{id: "toucannon", name: "Toucannon", dex: 733, cr: 45},
{id: "yungoos", name: "Yungoos", dex: 734, cr: 255},
{id: "gumshoos", name: "Gumshoos", dex: 735, cr: 127},
{id: "grubbin", name: "Grubbin", dex: 736, cr: 255},
{id: "charjabug", name: "Charjabug", dex: 737, cr: 120},
{id: "vikavolt", name: "Vikavolt", dex: 738, cr: 45},
{id: "crabrawler", name: "Crabrawler", dex: 739, cr: 225},
{id: "crabominable", name: "Crabominable", dex: 740, cr: 60},
{id: "oricorio", name: "Oricorio Baile Style", dex: 741, cr: 45},
{id: "cutiefly", name: "Cutiefly", dex: 742, cr: 190},
{id: "ribombee", name: "Ribombee", dex: 743, cr: 75},
{id: "rockruff", name: "Rockruff", dex: 744, cr: 190},
{id: "lycanroc", name: "Lycanroc", dex: 745, cr: 90},
{id: "wishiwashi", name: "Wishiwashi", dex: 746, cr: 60},
{id: "mareanie", name: "Mareanie", dex: 747, cr: 190},
{id: "toxapex", name: "Toxapex", dex: 748, cr: 75},
{id: "mudbray", name: "Mudbray", dex: 749, cr: 190},
{id: "mudsdale", name: "Mudsdale", dex: 750, cr: 60},
{id: "dewpider", name: "Dewpider", dex: 751, cr: 200},
{id: "araquanid", name: "Araquanid", dex: 752, cr: 100},
{id: "fomantis", name: "Fomantis", dex: 753, cr: 190},
{id: "lurantis", name: "Lurantis", dex: 754, cr: 75},
{id: "morelull", name: "Morelull", dex: 755, cr: 190},
{id: "shiinotic", name: "Shiinotic", dex: 756, cr: 75},
{id: "salandit", name: "Salandit", dex: 757, cr: 120},
{id: "salazzle", name: "Salazzle", dex: 758, cr: 45},
{id: "stufful", name: "Stufful", dex: 759, cr: 140},
{id: "bewear", name: "Bewear", dex: 760, cr: 70},
{id: "bounsweet", name: "Bounsweet", dex: 761, cr: 235},
{id: "steenee", name: "Steenee", dex: 762, cr: 120},
{id: "tsareena", name: "Tsareena", dex: 763, cr: 45},
{id: "comfey", name: "Comfey", dex: 764, cr: 60},
{id: "oranguru", name: "Oranguru", dex: 765, cr: 45},
{id: "passimian", name: "Passimian", dex: 766, cr: 45},
{id: "wimpod", name: "Wimpod", dex: 767, cr: 90},
{id: "golisopod", name: "Golisopod", dex: 768, cr: 45},
{id: "sandygast", name: "Sandygast", dex: 769, cr: 140},
{id: "palossand", name: "Palossand", dex: 770, cr: 60},
{id: "pyukumuku", name: "Pyukumuku", dex: 771, cr: 60},
{id: "type null", name: "Type: Null", dex: 772, cr: 3},
{id: "silvally", name: "Silvally", dex: 773, cr: 3},
{id: "minior", name: "Minior", dex: 774, cr: 30},
{id: "komala", name: "Komala", dex: 775, cr: 45},
{id: "turtonator", name: "Turtonator", dex: 776, cr: 70},
{id: "togedemaru", name: "Togedemaru", dex: 777, cr: 180},
{id: "mimikyu", name: "Mimikyu", dex: 778, cr: 45},
{id: "bruxish", name: "Bruxish", dex: 779, cr: 80},
{id: "drampa", name: "Drampa", dex: 780, cr: 70},
{id: "dhelmise", name: "Dhelmise", dex: 781, cr: 25},
{id: "jangmo-o", name: "Jangmo-o", dex: 782, cr: 45},
{id: "hakamo-o", name: "Hakamo-o", dex: 783, cr: 45},
{id: "kommo-o", name: "Kommo-o", dex: 784, cr: 45},
{id: "tapu koko", name: "Tapu Koko", dex: 785, cr: 3},
{id: "tapu lele", name: "Tapu Lele", dex: 786, cr: 3},
{id: "tapu bulu", name: "Tapu Bulu", dex: 787, cr: 3},
{id: "tapu fini", name: "Tapu Fini", dex: 788, cr: 3},
{id: "cosmog", name: "Cosmog", dex: 789, cr: 45},
{id: "cosmoem", name: "Cosmoem", dex: 790, cr: 45},
{id: "solgaleo", name: "Solgaleo", dex: 791, cr: 45},
{id: "lunala", name: "Lunala", dex: 792, cr: 45},
{id: "nihilego", name: "Nihilego", dex: 793, cr: 45},
{id: "buzzwole", name: "Buzzwole", dex: 794, cr: 25},
{id: "pheromosa", name: "Pheromosa", dex: 795, cr: 255},
{id: "xurkitree", name: "Xurkitree", dex: 796, cr: 30},
{id: "celesteela", name: "Celesteela", dex: 797, cr: 25},
{id: "kartana", name: "Kartana", dex: 798, cr: 255},
{id: "guzzlord", name: "Guzzlord", dex: 799, cr: 15},
{id: "necrozma", name: "Necrozma", dex: 800, cr: 3},
{id: "magearna", name: "Magearna", dex: 801, cr: 3},
{id: "marshadow", name: "Marshadow", dex: 802, cr: 3}];

for (var mon of mons){
	var opt = document.createElement("option");
	opt.text = mon.name;
	list.add(opt);
}

catchRate2.addEventListener("keyup", function(event) { //makes pressing enter in the textbox click submit
    event.preventDefault();
    if (event.keyCode == 13) {
        check.click();
    }
});